name: CI

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 #
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
        env:
          HD_S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY }}
          HD_S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
          HD_S3_FILES_BUCKET_NAME: ${{secrets.S3_FILES_BUCKET_NAME}}
          HD_BUCKET_NAME: ${{secrets.BUCKET_NAME}}
          HD_PASSWORD: ${{secrets.PASSWORD}}
          HD_LOCATION: ${{secrets.LOCATION}}
